spring:
  datasource:
    url: jdbc:h2:mem:peereval
    username: sa
    password:
    driver-class-name: org.h2.Driver
    mvc:
      cors:
        allowed-origins: http://localhost:5173
  jpa:
    show-sql: false
api:
  endpoint:
    base-url: /api/v1
server:
  port: 80
